### ISSUE TITLE
Uploading SARIF to Github code scanner

### ISSUE THREAD

**Issue by htadashi** [contractshark/pipeline-slither#3]
First of all, thanks for sharing this pipeline (as well the Echidna pipeline)! It greatly helped to setup an action in my repository too.

Slither 0.8.1 added SARIF support, so it is possible to integrate this action with [Github code scanner](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning).  I am not sure if this interest you, but this can be done by adding the following lines on the end of the action:

```
      - name: Run slither
        run: slither . --sarif slither.sarif || true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "slither.sarif"
```
